name: Java CI/CD with Gradle

on:
  push:
    branches:
      - 'ttest'
      - 'develop'

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Lint and format code
        run: ./gradlew editorconfigFormat

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 로 NCP 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_SSH_PASSWORD }}
          port: ${{ secrets.NCP_SSH_PORT}}
          script_stop: true
          script: |
            cd ./auction
            git pull knuk ttest
            ./gradlew build
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &

